export const ML_DECISION_REASON = {
  ML_ELIGIBLE: 'ML_ELIGIBLE',
  ML_INELIGIBLE_INSUFFICIENT_HISTORY: 'ML_INELIGIBLE_INSUFFICIENT_HISTORY',
  ML_INELIGIBLE_INSUFFICIENT_PERSISTENCE: 'ML_INELIGIBLE_INSUFFICIENT_PERSISTENCE',
  ML_INELIGIBLE_EVIDENCE_IMMATURE: 'ML_INELIGIBLE_EVIDENCE_IMMATURE',
  ML_INELIGIBLE_EVIDENCE_INVALID: 'ML_INELIGIBLE_EVIDENCE_INVALID',
  ML_INELIGIBLE_FEATURES_INCOMPLETE: 'ML_INELIGIBLE_FEATURES_INCOMPLETE',
  ML_INELIGIBLE_TELEMETRY_QUALITY: 'ML_INELIGIBLE_TELEMETRY_QUALITY',
  ML_INELIGIBLE_MODEL_VERSION_INCOMPATIBLE: 'ML_INELIGIBLE_MODEL_VERSION_INCOMPATIBLE',
  ML_INELIGIBLE_READINESS_NOT_READY: 'ML_INELIGIBLE_READINESS_NOT_READY',
  ML_INELIGIBLE_FEATURE_NAN: 'ML_INELIGIBLE_FEATURE_NAN',
  ML_INELIGIBLE_FEATURE_INFINITY: 'ML_INELIGIBLE_FEATURE_INFINITY',
  ML_INELIGIBLE_FEATURE_MALFORMED: 'ML_INELIGIBLE_FEATURE_MALFORMED',
  ML_INELIGIBLE_FEATURE_STALE: 'ML_INELIGIBLE_FEATURE_STALE',
  ML_INELIGIBLE_FEATURE_SCHEMA_MISMATCH: 'ML_INELIGIBLE_FEATURE_SCHEMA_MISMATCH',
  ML_INELIGIBLE_FEATURE_INTEGRITY_UNASSERTED:
    'ML_INELIGIBLE_FEATURE_INTEGRITY_UNASSERTED',
  ML_SKIPPED_FEATURE_UNAVAILABLE: 'ML_SKIPPED_FEATURE_UNAVAILABLE',
  ML_FAILED_SAFE_MODEL_UNAVAILABLE: 'ML_FAILED_SAFE_MODEL_UNAVAILABLE',
  ML_FAILED_SAFE_INFERENCE_ERROR: 'ML_FAILED_SAFE_INFERENCE_ERROR',
  ML_FAILED_SAFE_INFERENCE_TIMEOUT: 'ML_FAILED_SAFE_INFERENCE_TIMEOUT',
  ML_FAILED_SAFE_INVALID_OUTPUT: 'ML_FAILED_SAFE_INVALID_OUTPUT',
  ML_LOW_MODEL_CONFIDENCE: 'ML_LOW_MODEL_CONFIDENCE',
  ML_FALLBACK_DETERMINISTIC_RULES: 'ML_FALLBACK_DETERMINISTIC_RULES',
  ML_FALLBACK_OBSERVE: 'ML_FALLBACK_OBSERVE',
  ML_FALLBACK_REJECT: 'ML_FALLBACK_REJECT',
} as const;

export type MlDecisionReasonCode =
  (typeof ML_DECISION_REASON)[keyof typeof ML_DECISION_REASON];
