/**
 * Standard audit event names used across the SISU'M backend.
 *
 * Keep event names stable because CloudWatch Logs Insights queries,
 * alarms, dashboards, and future persistence may depend on them.
 */
export const AUDIT_EVENTS = {
  REQUEST_STARTED: 'request.started',
  REQUEST_COMPLETED: 'request.completed',
  REQUEST_FAILED: 'request.failed',
  AUTHORIZATION_DENIED: 'authorization.denied',
  IDENTITY_MISSING: 'identity.missing',
  ROLE_UNRECOGNIZED: 'role.unrecognized',
  WORKFLOW_STARTED: 'workflow.started',
  WORKFLOW_COMPLETED: 'workflow.completed',
  WORKFLOW_FAILED: 'workflow.failed',
  WORKFLOW_DUPLICATE_DETECTED: 'workflow.duplicate_detected',
  REPORT_GENERATED: 'report.generated',
  REPORT_GENERATION_FAILED: 'report.generation_failed',
  EXECUTION_SIMULATED: 'execution.simulated',
  EXECUTION_SIMULATION_FAILED: 'execution.simulation_failed',
  EXECUTION_STARTED: 'execution.started',
  EXECUTION_SUCCEEDED: 'execution.succeeded',
  EXECUTION_FAILED: 'execution.failed',
  ROLLBACK_STARTED: 'rollback.started',
  ROLLBACK_COMPLETED: 'rollback.completed',
  ROLLBACK_FAILED: 'rollback.failed',
  EXECUTION_PLAN_CREATED: 'execution.plan.created',
  EXECUTION_PLAN_UPDATED: 'execution.plan.updated',
  EXECUTION_APPROVED: 'execution.approved',
  EXECUTION_REJECTED: 'execution.rejected',
  EXECUTION_EXECUTED: 'execution.executed',
  EXECUTION_EXECUTION_FAILED: 'execution.execution_failed',
  EXECUTION_ROLLBACK_REQUESTED: 'execution.rollback_requested',
  EXECUTION_ROLLED_BACK: 'execution.rolled_back',
  EXECUTION_ROLLBACK_FAILED: 'execution.rollback_failed',
  AUDIT_SEARCH_PERFORMED: 'audit.search_performed',
  AUDIT_PERSISTENCE_FAILED: 'audit.persistence_failed',
  TENANT_CLAIM_MISSING: 'tenant.claim_missing',
  TENANT_FALLBACK_USED: 'tenant.fallback_used',
  TENANT_ACCESS_DENIED: 'tenant.access_denied',
  
  MEMBER_ADDED: 'member.added',
  MEMBER_UPDATED: 'member.updated',
  MEMBER_SUSPENDED: 'member.suspended',
  MEMBER_REACTIVATED: 'member.reactivated',
  MEMBER_REMOVED: 'member.removed',
  MEMBER_ACTION_FAILED: 'member.action_failed',
  INVITATION_CREATED: 'invitation.created',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_CANCELLED: 'invitation.cancelled',
  INVITATION_ACTION_FAILED: 'invitation.action_failed',

  TENANT_CREATED: 'tenant.created',
  TENANT_UPDATED: 'tenant.updated',
  TENANT_SUSPENDED: 'tenant.suspended',
  TENANT_REACTIVATED: 'tenant.reactivated',
  TENANT_ARCHIVED: 'tenant.archived',
  TENANT_DELETED: 'tenant.deleted',
  TENANT_ADMINISTRATION_DENIED: 'tenant.administration_denied',
  PRIVILEGED_MFA_REQUIRED: 'privileged.mfa_required',
  PRIVILEGED_MFA_VERIFIED: 'privileged.mfa_verified',
  PRIVILEGED_MFA_DENIED: 'privileged.mfa_denied',

  ASSUME_ROLE_STARTED: 'assume_role.started',
  ASSUME_ROLE_SUCCEEDED: 'assume_role.succeeded',
  ASSUME_ROLE_FAILED: 'assume_role.failed',

  ACCOUNT_REGISTERED: 'aws_account.registered',
  ACCOUNT_VERIFIED: 'aws_account.verified',
  ACCOUNT_UPDATED: 'aws_account.updated',
  ACCOUNT_REMOVED: 'aws_account.removed',
  ACCOUNT_ACTION_FAILED: 'aws_account.action_failed',
  COST_INTELLIGENCE_ANALYSIS_STARTED: 'cost_intelligence.analysis_started',
  COST_INTELLIGENCE_ANALYSIS_COMPLETED: 'cost_intelligence.analysis_completed',
  COST_INTELLIGENCE_ANALYSIS_FAILED: 'cost_intelligence.analysis_failed',
  COST_INTELLIGENCE_FINDING_STATUS_UPDATED: 'cost_intelligence.finding_status_updated',
} as const;
export type AuditEventName =
  (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];
