/**
 * Standard audit event names used across the SISU'M backend.
 *
 * Keep event names stable because CloudWatch Logs Insights queries,
 * alarms, dashboards, and future persistence may depend on them.
 */
export const AUDIT_EVENTS = {
  REQUEST_STARTED: 'request.started',
  REQUEST_COMPLETED: 'request.completed',
  REQUEST_FAILED: 'request.failed',
  AUTHORIZATION_DENIED: 'authorization.denied',
  IDENTITY_MISSING: 'identity.missing',
  ROLE_UNRECOGNIZED: 'role.unrecognized',
  WORKFLOW_STARTED: 'workflow.started',
  WORKFLOW_COMPLETED: 'workflow.completed',
  WORKFLOW_FAILED: 'workflow.failed',
  WORKFLOW_DUPLICATE_DETECTED: 'workflow.duplicate_detected',
  REPORT_GENERATED: 'report.generated',
  REPORT_GENERATION_FAILED: 'report.generation_failed',
  EXECUTION_SIMULATED: 'execution.simulated',
  EXECUTION_SIMULATION_FAILED: 'execution.simulation_failed',
  EXECUTION_STARTED: 'execution.started',
  EXECUTION_SUCCEEDED: 'execution.succeeded',
  EXECUTION_FAILED: 'execution.failed',
  ROLLBACK_STARTED: 'rollback.started',
  ROLLBACK_COMPLETED: 'rollback.completed',
  ROLLBACK_FAILED: 'rollback.failed',
  EXECUTION_PLAN_CREATED: 'execution.plan.created',
  EXECUTION_PLAN_UPDATED: 'execution.plan.updated',
  EXECUTION_APPROVED: 'execution.approved',
  EXECUTION_REJECTED: 'execution.rejected',
  EXECUTION_EXECUTED: 'execution.executed',
  EXECUTION_EXECUTION_FAILED: 'execution.execution_failed',
  EXECUTION_ROLLBACK_REQUESTED: 'execution.rollback_requested',
  EXECUTION_ROLLED_BACK: 'execution.rolled_back',
  EXECUTION_ROLLBACK_FAILED: 'execution.rollback_failed',
  AUDIT_SEARCH_PERFORMED: 'audit.search_performed',
  AUDIT_PERSISTENCE_FAILED: 'audit.persistence_failed',
  TENANT_CLAIM_MISSING: 'tenant.claim_missing',
  TENANT_FALLBACK_USED: 'tenant.fallback_used',
  TENANT_ACCESS_DENIED: 'tenant.access_denied',
  
  MEMBER_ADDED: 'member.added',
  MEMBER_UPDATED: 'member.updated',
  MEMBER_SUSPENDED: 'member.suspended',
  MEMBER_REACTIVATED: 'member.reactivated',
  MEMBER_REMOVED: 'member.removed',
  MEMBER_ACTION_FAILED: 'member.action_failed',
  INVITATION_CREATED: 'invitation.created',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_CANCELLED: 'invitation.cancelled',
  INVITATION_ACTION_FAILED: 'invitation.action_failed',

  TENANT_CREATED: 'tenant.created',
  TENANT_ONBOARDING_STARTED: 'tenant.onboarding_started',
  TENANT_IDENTITY_ASSIGNMENT_STARTED: 'tenant.identity_assignment_started',
  TENANT_IDENTITY_ASSIGNMENT_SUCCEEDED: 'tenant.identity_assignment_succeeded',
  TENANT_IDENTITY_ASSIGNMENT_FAILED: 'tenant.identity_assignment_failed',
  TENANT_ONBOARDING_COMPLETED: 'tenant.onboarding_completed',
  TENANT_ONBOARDING_RETRY_STARTED: 'tenant.onboarding_retry_started',
  TENANT_ONBOARDING_RETRY_COMPLETED: 'tenant.onboarding_retry_completed',
  TENANT_ONBOARDING_DENIED: 'tenant.onboarding_denied',
  TENANT_UPDATED: 'tenant.updated',
  TENANT_SUSPENDED: 'tenant.suspended',
  TENANT_REACTIVATED: 'tenant.reactivated',
  TENANT_ARCHIVED: 'tenant.archived',
  TENANT_DELETED: 'tenant.deleted',
  TENANT_ADMINISTRATION_DENIED: 'tenant.administration_denied',
  TENANT_OWNER_BOOTSTRAP_STARTED: 'tenant.owner_bootstrap_started',
  TENANT_OWNER_BOOTSTRAP_SUCCEEDED: 'tenant.owner_bootstrap_succeeded',
  TENANT_OWNER_BOOTSTRAP_FAILED: 'tenant.owner_bootstrap_failed',
  TENANT_OWNER_BOOTSTRAP_DENIED: 'tenant.owner_bootstrap_denied',
  PRIVILEGED_MFA_REQUIRED: 'privileged.mfa_required',
  PRIVILEGED_MFA_VERIFIED: 'privileged.mfa_verified',
  PRIVILEGED_MFA_DENIED: 'privileged.mfa_denied',

  ASSUME_ROLE_STARTED: 'assume_role.started',
  ASSUME_ROLE_SUCCEEDED: 'assume_role.succeeded',
  ASSUME_ROLE_FAILED: 'assume_role.failed',

  ACCOUNT_REGISTERED: 'aws_account.registered',
  ACCOUNT_VERIFIED: 'aws_account.verified',
  ACCOUNT_UPDATED: 'aws_account.updated',
  ACCOUNT_REMOVED: 'aws_account.removed',
  ACCOUNT_ACTION_FAILED: 'aws_account.action_failed',
  ACCOUNT_DISCOVERY_STARTED: 'aws_account.discovery_started',
  ACCOUNT_DISCOVERY_SUCCEEDED: 'aws_account.discovery_succeeded',
  ACCOUNT_DISCOVERY_FAILED: 'aws_account.discovery_failed',
  ACCOUNT_IDENTITY_MISMATCH: 'aws_account.identity_mismatch',
  EC2_DISCOVERY_STARTED: 'ec2.discovery_started',
  EC2_DISCOVERY_SUCCEEDED: 'ec2.discovery_succeeded',
  EC2_DISCOVERY_PARTIAL: 'ec2.discovery_partial',
  EC2_DISCOVERY_FAILED: 'ec2.discovery_failed',
  EC2_RESOURCE_LISTED: 'ec2.resource_listed',
  EC2_RESOURCE_VIEWED: 'ec2.resource_viewed',
  EC2_DISCOVERY_DENIED: 'ec2.discovery_denied',
  EC2_COST_ANALYSIS_STARTED: 'ec2.cost_analysis_started',
  EC2_COST_ANALYSIS_SUCCEEDED: 'ec2.cost_analysis_succeeded',
  EC2_COST_ANALYSIS_PARTIAL: 'ec2.cost_analysis_partial',
  EC2_COST_ANALYSIS_FAILED: 'ec2.cost_analysis_failed',
  EC2_COST_RECOMMENDATIONS_LISTED: 'ec2.cost_recommendations_listed',
  EC2_COST_RECOMMENDATION_VIEWED: 'ec2.cost_recommendation_viewed',
  EC2_SECURITY_ANALYSIS_STARTED: 'ec2.security_analysis_started',
  EC2_SECURITY_ANALYSIS_SUCCEEDED: 'ec2.security_analysis_succeeded',
  EC2_SECURITY_ANALYSIS_PARTIAL: 'ec2.security_analysis_partial',
  EC2_SECURITY_ANALYSIS_FAILED: 'ec2.security_analysis_failed',
  EC2_SECURITY_FINDINGS_LISTED: 'ec2.security_findings_listed',
  EC2_SECURITY_SUMMARY_VIEWED: 'ec2.security_summary_viewed',
  EC2_ASYNC_JOB_CREATED: 'ec2.async_job_created',
  EC2_ASYNC_JOB_ENQUEUED: 'ec2.async_job_enqueued',
  EC2_ASYNC_JOB_ENQUEUE_FAILED: 'ec2.async_job_enqueue_failed',
  EC2_ASYNC_JOB_LISTED: 'ec2.async_job_listed',
  EC2_ASYNC_JOB_VIEWED: 'ec2.async_job_viewed',
  EC2_ASYNC_JOB_EVENTS_VIEWED: 'ec2.async_job_events_viewed',
  EC2_ASYNC_JOB_STARTED: 'ec2.async_job_started',
  EC2_ASYNC_JOB_RETRYING: 'ec2.async_job_retrying',
  EC2_ASYNC_JOB_SUCCEEDED: 'ec2.async_job_succeeded',
  EC2_ASYNC_JOB_FAILED: 'ec2.async_job_failed',
} as const;
export type AuditEventName =
  (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];
