version = 0.1

[default.deploy.parameters]
stack_name = "sisum-backend"
resolve_s3 = false
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jvcpwlm12nru"
s3_prefix = "sisum-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\" ProviderMode=\"mock\" CorsOrigin=\"https://elitewebservices.org\" LogLevel=\"info\" CognitoUserPoolId=\"us-east-1_DARrpLb5p\" CognitoUserPoolClientId=\"1dc1g0tkflsspjd7uc6n131jft\" AuditRetentionDays=\"365\" AuditPersistenceEnabled=\"true\" DefaultTenantId=\"sisum-default\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
