export const PROVENANCE_REASON = {
  PROVENANCE_APPROVAL_MISSING: 'PROVENANCE_APPROVAL_MISSING',
  PROVENANCE_EXECUTION_MISSING: 'PROVENANCE_EXECUTION_MISSING',
  PROVENANCE_VERIFICATION_MISSING: 'PROVENANCE_VERIFICATION_MISSING',
  PROVENANCE_ROLLBACK_MISSING: 'PROVENANCE_ROLLBACK_MISSING',
  PROVENANCE_SOURCE_RECORD_UNAVAILABLE: 'PROVENANCE_SOURCE_RECORD_UNAVAILABLE',
  PROVENANCE_SOURCE_RECORD_NOT_VERIFIED: 'PROVENANCE_SOURCE_RECORD_NOT_VERIFIED',
  PROVENANCE_CORRELATION_GAP: 'PROVENANCE_CORRELATION_GAP',
  PROVENANCE_LIFECYCLE_NOT_FOUND: 'PROVENANCE_LIFECYCLE_NOT_FOUND',
  PROVENANCE_DECISION_SCOPE_MISMATCH: 'PROVENANCE_DECISION_SCOPE_MISMATCH',
  PROVENANCE_TENANT_SCOPE_VIOLATION: 'PROVENANCE_TENANT_SCOPE_VIOLATION',
  PROVENANCE_ACCOUNT_SCOPE_VIOLATION: 'PROVENANCE_ACCOUNT_SCOPE_VIOLATION',
  PROVENANCE_OPTIONAL_COST_EVIDENCE_MISSING: 'PROVENANCE_OPTIONAL_COST_EVIDENCE_MISSING',
  PROVENANCE_OPTIONAL_LEARNING_MISSING: 'PROVENANCE_OPTIONAL_LEARNING_MISSING',
  PROVENANCE_ML_PATH_VALID: 'PROVENANCE_ML_PATH_VALID',
  PROVENANCE_SIMULATION_PATH: 'PROVENANCE_SIMULATION_PATH',
  PROVENANCE_COMPLETE: 'PROVENANCE_COMPLETE',
} as const;

export type ProvenanceReasonCode =
  (typeof PROVENANCE_REASON)[keyof typeof PROVENANCE_REASON];
