export const ROLLBACK_AUTHORIZATION_REASON = {
  DENIED_NOT_ROLLBACK_CANDIDATE: 'ROLLBACK_AUTH_DENIED_NOT_ROLLBACK_CANDIDATE',
  DENIED_EVIDENCE_INSUFFICIENT: 'ROLLBACK_AUTH_DENIED_EVIDENCE_INSUFFICIENT',
  DENIED_ML_CANNOT_AUTHORIZE: 'ROLLBACK_AUTH_DENIED_ML_CANNOT_AUTHORIZE',
  DENIED_VERIFICATION_CANNOT_INVOKE_DIRECTLY:
    'ROLLBACK_AUTH_DENIED_VERIFICATION_CANNOT_INVOKE_DIRECTLY',
  DENIED_ACTOR_UNAUTHORIZED: 'ROLLBACK_AUTH_DENIED_ACTOR_UNAUTHORIZED',
  DENIED_MFA_REQUIRED: 'ROLLBACK_AUTH_DENIED_MFA_REQUIRED',
  DENIED_CROSS_TENANT: 'ROLLBACK_AUTH_DENIED_CROSS_TENANT',
  DENIED_EXECUTION_NOT_ROLLBACK_ELIGIBLE_STATE:
    'ROLLBACK_AUTH_DENIED_EXECUTION_NOT_ROLLBACK_ELIGIBLE_STATE',
  DENIED_ALREADY_ROLLED_BACK: 'ROLLBACK_AUTH_DENIED_ALREADY_ROLLED_BACK',
  AUTHORIZED_HUMAN_ACTOR: 'ROLLBACK_AUTH_AUTHORIZED_HUMAN_ACTOR',
} as const;

export type RollbackAuthorizationReasonCode =
  (typeof ROLLBACK_AUTHORIZATION_REASON)[keyof typeof ROLLBACK_AUTHORIZATION_REASON];
