export const GOVERNANCE_CONVERGENCE_REASON = {
  CONTROL_STILL_SATISFIED: 'GOVERNANCE_CONTROL_STILL_SATISFIED',
  VIOLATION_PERSISTS_UNCHANGED: 'GOVERNANCE_VIOLATION_PERSISTS_UNCHANGED',
  EVIDENCE_UNAVAILABLE_UNCHANGED: 'GOVERNANCE_EVIDENCE_UNAVAILABLE_UNCHANGED',
  VIOLATION_RESOLVED: 'GOVERNANCE_VIOLATION_RESOLVED',
  MECHANISM_STRENGTHENED: 'GOVERNANCE_MECHANISM_STRENGTHENED',
  MECHANISM_CHANGED_STILL_SATISFIED: 'GOVERNANCE_MECHANISM_CHANGED_STILL_SATISFIED',
  VIOLATION_CONTENT_CHANGED: 'GOVERNANCE_VIOLATION_CONTENT_CHANGED',
  CONTROL_REGRESSED: 'GOVERNANCE_CONTROL_REGRESSED',
  CURRENT_EVIDENCE_ABSENT: 'GOVERNANCE_CURRENT_EVIDENCE_ABSENT',
  DUPLICATE_LOGICAL_OBSERVATION: 'GOVERNANCE_DUPLICATE_LOGICAL_OBSERVATION',
  INVALID_OBSERVATION_TIMESTAMP: 'GOVERNANCE_INVALID_OBSERVATION_TIMESTAMP',
  MISSING_OBSERVATION_TIMESTAMP: 'GOVERNANCE_MISSING_OBSERVATION_TIMESTAMP',
} as const;

export type GovernanceConvergenceReasonCode =
  (typeof GOVERNANCE_CONVERGENCE_REASON)[keyof typeof GOVERNANCE_CONVERGENCE_REASON];
