/**
 * Sprint 3 failure/degradation matrix — exactly 19 rows.
 * Each row documents construction, degradation, lifecycle state, and PASS/PARTIAL/MISSING.
 */
export const SPRINT3_FAILURE_DEGRADATION_MATRIX = [
  {
    row: 1,
    scenario: 'insufficient ML observations',
    testFile: 'tests/unit/ml-eligibility-policy.test.ts',
    testName: 'returns ML_INELIGIBLE when stable epoch observation count is insufficient',
    failureConstruction: 'featureManifest.stableEpochObservationCount below threshold',
    expectedDegradation: 'ML_INELIGIBLE → DETERMINISTIC_RULES',
    expectedFinalLifecycleState: 'READY + ML_SKIPPED + approval preserved',
    reasonCodes: ['ML_INELIGIBLE'],
    idempotencyExpectation: 'stable evaluationId',
    tenantAccountExpectation: 'tenant/account scoped input',
    status: 'PASS',
  },
  {
    row: 2,
    scenario: 'missing ML feature',
    testFile: 'tests/unit/ml-eligibility-policy.test.ts',
    testName: 'returns ML_INELIGIBLE when featuresComplete is false',
    failureConstruction: 'featureManifest.featuresComplete = false',
    expectedDegradation: 'ML_INELIGIBLE',
    expectedFinalLifecycleState: 'policy uses deterministic rules',
    reasonCodes: ['ML_INELIGIBLE'],
    idempotencyExpectation: 'stable evaluationId',
    tenantAccountExpectation: 'scoped feature context',
    status: 'PASS',
  },
  {
    row: 3,
    scenario: 'model unavailable',
    testFile: 'tests/integration/sprint-3-ml-no-ml-golden.test.ts',
    testName: 'READY + model unavailable → FAILED_SAFE → DETERMINISTIC_RULES → approval still REQUIRED',
    failureConstruction: 'UnavailableMlInferenceAdapter',
    expectedDegradation: 'ML_FAILED_SAFE',
    expectedFinalLifecycleState: 'approval REQUIRED, execution NOT_ELIGIBLE without approval',
    reasonCodes: ['ML_MODEL_UNAVAILABLE'],
    idempotencyExpectation: 'stable evaluationId',
    tenantAccountExpectation: 'tenant-a/account-a',
    status: 'PASS',
  },
  {
    row: 4,
    scenario: 'inference error',
    testFile: 'tests/unit/ml-decision-service.test.ts',
    testName: 'FAILED_SAFE on adapter inference throw',
    failureConstruction: 'mock adapter throws',
    expectedDegradation: 'ML_FAILED_SAFE → DETERMINISTIC_RULES',
    expectedFinalLifecycleState: 'no autonomous execution',
    reasonCodes: ['ML_INFERENCE_ERROR'],
    idempotencyExpectation: 'stable evaluationId',
    tenantAccountExpectation: 'scoped model context',
    status: 'PASS',
  },
  {
    row: 5,
    scenario: 'corrupt ML output',
    testFile: 'tests/unit/ml-output-validation.test.ts',
    testName: 'rejects corrupt adapter payload',
    failureConstruction: 'invalid confidence/outcome payload',
    expectedDegradation: 'ML_FAILED_SAFE',
    expectedFinalLifecycleState: 'deterministic fallback',
    reasonCodes: ['ML_OUTPUT_INVALID'],
    idempotencyExpectation: 'stable evaluationId',
    tenantAccountExpectation: 'scoped input',
    status: 'PASS',
  },
  {
    row: 6,
    scenario: 'low model confidence',
    testFile: 'tests/unit/ml-output-validation.test.ts',
    testName: 'rejects confidence below contract threshold',
    failureConstruction: 'modelConfidence below minimum',
    expectedDegradation: 'ML_FAILED_SAFE or SKIPPED',
    expectedFinalLifecycleState: 'approval unchanged',
    reasonCodes: ['ML_OUTPUT_INVALID'],
    idempotencyExpectation: 'stable evaluationId',
    tenantAccountExpectation: 'scoped input',
    status: 'PASS',
  },
  {
    row: 7,
    scenario: 'missing approval',
    testFile: 'tests/integration/sprint-3-approval-action-policy-workflow.test.ts',
    testName: 'production execution remains NOT_ELIGIBLE without approval',
    failureConstruction: 'approvalStatus missing',
    expectedDegradation: 'NOT_ELIGIBLE',
    expectedFinalLifecycleState: 'blocked before execution',
    reasonCodes: ['APPROVAL_REQUIRED'],
    idempotencyExpectation: 'duplicate approval request idempotent',
    tenantAccountExpectation: 'tenant scoped',
    status: 'PASS',
  },
  {
    row: 8,
    scenario: 'rejected approval',
    testFile: 'tests/integration/sprint-3-approval-action-policy-workflow.test.ts',
    testName: 'rejected approval blocks production execution eligibility',
    failureConstruction: 'approvalStatus REJECTED',
    expectedDegradation: 'NOT_ELIGIBLE',
    expectedFinalLifecycleState: 'execution blocked',
    reasonCodes: ['APPROVAL_REJECTED'],
    idempotencyExpectation: 'n/a',
    tenantAccountExpectation: 'tenant scoped',
    status: 'PASS',
  },
  {
    row: 9,
    scenario: 'duplicate approval request',
    testFile: 'tests/integration/sprint-3-approval-action-policy-workflow.test.ts',
    testName: 'DUPLICATE_APPROVAL_IDEMPOTENT rejects second approval attempt',
    failureConstruction: 'repeat approval with same idempotency key',
    expectedDegradation: 'idempotent reject',
    expectedFinalLifecycleState: 'single approval record',
    reasonCodes: ['DUPLICATE_APPROVAL_IDEMPOTENT'],
    idempotencyExpectation: 'second attempt rejected',
    tenantAccountExpectation: 'tenant scoped',
    status: 'PASS',
  },
  {
    row: 10,
    scenario: 'duplicate execution request',
    testFile: 'tests/integration/execution-api-concurrency.test.ts',
    testName: 'duplicate execution idempotency',
    failureConstruction: 'repeat execution with same idempotency key',
    expectedDegradation: 'idempotent response',
    expectedFinalLifecycleState: 'single logical execution',
    reasonCodes: ['DUPLICATE_EXECUTION'],
    idempotencyExpectation: 'no duplicate logical production action',
    tenantAccountExpectation: 'tenant scoped',
    status: 'PASS',
  },
  {
    row: 11,
    scenario: 'execution provider failure',
    testFile: 'tests/integration/sprint-3-execution-provider-failure-verification.test.ts',
    testName: 'approved eligible candidate → provider execute fails → verification is not RESOLVED or HEALTHY',
    failureConstruction: 'orchestrator adapter execute returns success:false with EXECUTION_FAILED',
    expectedDegradation: 'execution FAILED → verification INSUFFICIENT_EVIDENCE',
    expectedFinalLifecycleState: 'FAILED run persisted; verification not RESOLVED/HEALTHY',
    reasonCodes: ['EXECUTION_NOT_COMPLETED', 'INSUFFICIENT_EVIDENCE', 'LEGACY_PENDING'],
    idempotencyExpectation: 'stable runId and assessmentId on retry',
    tenantAccountExpectation: 'tenant/account scoped orchestrator + verification',
    status: 'PASS',
  },
  {
    row: 12,
    scenario: 'verification telemetry missing',
    testFile: 'tests/unit/post-action-verification-assessment.test.ts',
    testName: 'COMPLETED + telemetry missing → INSUFFICIENT_EVIDENCE',
    failureConstruction: 'telemetry.available null/false, after evidence null',
    expectedDegradation: 'INSUFFICIENT_EVIDENCE',
    expectedFinalLifecycleState: 'VERIFICATION_INSUFFICIENT_EVIDENCE ActionLog event',
    reasonCodes: ['TELEMETRY_MISSING'],
    idempotencyExpectation: 'stable assessmentId',
    tenantAccountExpectation: 'explicit tenant/account scope',
    status: 'PASS',
  },
  {
    row: 13,
    scenario: 'post-action degradation',
    testFile: 'tests/unit/post-action-verification-assessment.test.ts',
    testName: 'COMPLETED + degraded telemetry → DEGRADED or ROLLBACK_CANDIDATE',
    failureConstruction: 'telemetry.degraded true + comparator failure',
    expectedDegradation: 'DEGRADED / ROLLBACK_CANDIDATE advisory',
    expectedFinalLifecycleState: 'not RESOLVED',
    reasonCodes: ['TELEMETRY_DEGRADED', 'MEASURABLE_DEGRADATION'],
    idempotencyExpectation: 'stable assessmentId',
    tenantAccountExpectation: 'scoped evidence references',
    status: 'PASS',
  },
  {
    row: 14,
    scenario: 'recommendation not resolved',
    testFile: 'tests/unit/post-action-verification-assessment.test.ts',
    testName: 'COMPLETED + expected state + healthy telemetry + recommendation persists → HEALTHY, not RESOLVED',
    failureConstruction: 'recommendationState.present true',
    expectedDegradation: 'HEALTHY (non-resolved)',
    expectedFinalLifecycleState: 'recommendation persists',
    reasonCodes: ['RECOMMENDATION_PERSISTS'],
    idempotencyExpectation: 'stable assessmentId',
    tenantAccountExpectation: 'explicit recommendation evidence reference',
    status: 'PASS',
  },
  {
    row: 15,
    scenario: 'ActionLog persistence failure',
    testFile: 'tests/integration/sprint-3-verification-actionlog-persistence-failure.test.ts',
    testName: 'authoritative verification persisted → ActionLog emission fails → assessment intact → retry idempotent',
    failureConstruction: 'ActionLog repository throws on recordEvent during emitAfterPostActionVerification',
    expectedDegradation: 'ActionLogPersistenceError; verification assessment unchanged',
    expectedFinalLifecycleState: 'verification persisted; ActionLog gap until successful retry',
    reasonCodes: ['HEALTHY_POST_ACTION', 'RECOMMENDATION_PERSISTS'],
    idempotencyExpectation: 'retry emits two events once; duplicate retry created:false',
    tenantAccountExpectation: 'tenant/account preserved in verification and ActionLog input',
    status: 'PASS',
  },
  {
    row: 16,
    scenario: 'duplicate ActionLog event',
    testFile: 'tests/integration/sprint-3-verification-actionlog-integration.test.ts',
    testName: 'duplicate ActionLog emission remains idempotent via repository identity',
    failureConstruction: 'repeat emitAfterPostActionVerification with same assessmentId',
    expectedDegradation: 'idempotent record',
    expectedFinalLifecycleState: 'single logical event per identity',
    reasonCodes: [],
    idempotencyExpectation: 'created:false on duplicate',
    tenantAccountExpectation: 'tenant scoped canonical key',
    status: 'PASS',
  },
  {
    row: 17,
    scenario: 'cross-tenant approval attempt',
    testFile: 'tests/security/sprint-3-approval-action-policy-authorization.test.ts',
    testName: 'cross-tenant approval denied',
    failureConstruction: 'tenant B actor on tenant A resource',
    expectedDegradation: 'authorization denied / safe 404',
    expectedFinalLifecycleState: 'no approval granted',
    reasonCodes: ['TENANT_ACCESS_DENIED'],
    idempotencyExpectation: 'n/a',
    tenantAccountExpectation: 'strict tenant boundary',
    status: 'PASS',
  },
  {
    row: 18,
    scenario: 'cross-tenant execution attempt',
    testFile: 'tests/integration/sprint-3-approval-action-policy-legacy-safety.test.ts',
    testName: 'legacy cross-tenant execution is denied',
    failureConstruction: 'tenant B execution on tenant A plan',
    expectedDegradation: 'safe denial',
    expectedFinalLifecycleState: 'no production execution',
    reasonCodes: ['TENANT_ACCESS_DENIED'],
    idempotencyExpectation: 'n/a',
    tenantAccountExpectation: 'strict tenant boundary',
    status: 'PASS',
  },
  {
    row: 19,
    scenario: 'cross-tenant verification lookup',
    testFile: 'tests/integration/sprint-3-verification-tenant-isolation.test.ts',
    testName: 'cross-tenant verification lookup returns safe not-found',
    failureConstruction: 'tenant B lookup of tenant A workflow/execution',
    expectedDegradation: 'undefined / safe not-found',
    expectedFinalLifecycleState: 'no evidence leak',
    reasonCodes: [],
    idempotencyExpectation: 'n/a',
    tenantAccountExpectation: 'tenant partition enforced',
    status: 'PASS',
  },
] as const;

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

describe('Sprint 3 failure/degradation matrix catalogue', () => {
  it('defines exactly 19 unique rows', () => {
    assert.equal(SPRINT3_FAILURE_DEGRADATION_MATRIX.length, 19);
    const rows = SPRINT3_FAILURE_DEGRADATION_MATRIX.map((entry) => entry.row);
    assert.deepEqual(rows, Array.from({ length: 19 }, (_, index) => index + 1));
  });

  it('requires 19 PASS with zero PARTIAL or MISSING rows', () => {
    assert.equal(SPRINT3_FAILURE_DEGRADATION_MATRIX.length, 19);
    for (const entry of SPRINT3_FAILURE_DEGRADATION_MATRIX) {
      assert.equal(entry.status, 'PASS');
    }
  });
});
