export const MATURITY_REASON = {
  FIRST_OBSERVATION: 'MATURITY_FIRST_OBSERVATION',
  PRIOR_HISTORY_MISSING: 'MATURITY_PRIOR_HISTORY_MISSING',
  FINGERPRINT_CHANGED_RESET: 'MATURITY_FINGERPRINT_CHANGED_RESET',
  INSUFFICIENT_OBSERVATION_COUNT: 'MATURITY_INSUFFICIENT_OBSERVATION_COUNT',
  SUFFICIENT_OBSERVATION_COUNT: 'MATURITY_SUFFICIENT_OBSERVATION_COUNT',
  INSUFFICIENT_STABLE_EPOCH_DURATION: 'MATURITY_INSUFFICIENT_STABLE_EPOCH_DURATION',
  SUFFICIENT_STABLE_EPOCH_DURATION: 'MATURITY_SUFFICIENT_STABLE_EPOCH_DURATION',
  STABLE_HISTORY_SUPPORTS_PARTIAL: 'MATURITY_STABLE_HISTORY_SUPPORTS_PARTIAL',
  STABLE_HISTORY_SUPPORTS_MATURE: 'MATURITY_STABLE_HISTORY_SUPPORTS_MATURE',
  TELEMETRY_COMPLETE: 'MATURITY_TELEMETRY_COMPLETE',
  TELEMETRY_PARTIAL: 'MATURITY_TELEMETRY_PARTIAL',
  TELEMETRY_INSUFFICIENT: 'MATURITY_TELEMETRY_INSUFFICIENT',
  TELEMETRY_NO_DATA: 'MATURITY_TELEMETRY_NO_DATA',
  TELEMETRY_NOT_APPLICABLE: 'MATURITY_TELEMETRY_NOT_APPLICABLE',
  DUPLICATE_EVALUATION: 'MATURITY_DUPLICATE_EVALUATION',
} as const;

export type EvidenceMaturityReasonCode = (typeof MATURITY_REASON)[keyof typeof MATURITY_REASON];
