export const CONFIDENCE_REASON = {
  PERSISTENCE_STABLE: 'CONFIDENCE_PERSISTENCE_STABLE',
  PERSISTENCE_NEW: 'CONFIDENCE_PERSISTENCE_NEW',
  PERSISTENCE_CHANGED: 'CONFIDENCE_PERSISTENCE_CHANGED',
  PERSISTENCE_MISSING_PREVIOUS: 'CONFIDENCE_PERSISTENCE_MISSING_PREVIOUS',
  PERSISTENCE_HISTORY_ABSENT: 'CONFIDENCE_PERSISTENCE_HISTORY_ABSENT',
  PERSISTENCE_PROVIDER_HINT_FALLBACK: 'CONFIDENCE_PERSISTENCE_PROVIDER_HINT_FALLBACK',
  PERSISTENCE_MATURITY_STATE_MISMATCH: 'CONFIDENCE_PERSISTENCE_MATURITY_STATE_MISMATCH',
  PERSISTENCE_HOURS_MISMATCH: 'CONFIDENCE_PERSISTENCE_HOURS_MISMATCH',
  MATURITY_SOURCE_OBSERVATION_MISMATCH: 'CONFIDENCE_MATURITY_SOURCE_OBSERVATION_MISMATCH',

  MATURITY_MATURE: 'CONFIDENCE_MATURITY_MATURE',
  MATURITY_PARTIAL: 'CONFIDENCE_MATURITY_PARTIAL',
  MATURITY_IMMATURE: 'CONFIDENCE_MATURITY_IMMATURE',

  TELEMETRY_NO_DATA: 'CONFIDENCE_TELEMETRY_NO_DATA',
  TELEMETRY_PARTIAL: 'CONFIDENCE_TELEMETRY_PARTIAL',
  TELEMETRY_INSUFFICIENT: 'CONFIDENCE_TELEMETRY_INSUFFICIENT',
  TELEMETRY_NOT_APPLICABLE: 'CONFIDENCE_TELEMETRY_NOT_APPLICABLE',

  METRICS_PARTIAL: 'CONFIDENCE_METRICS_PARTIAL',
  OBSERVATION_WINDOW_INSUFFICIENT: 'CONFIDENCE_OBSERVATION_WINDOW_INSUFFICIENT',

  GOVERNANCE_CONTEXT_MISSING: 'CONFIDENCE_GOVERNANCE_CONTEXT_MISSING',

  STATUS_CEILING_APPLIED: 'CONFIDENCE_STATUS_CEILING_APPLIED',
  LEGACY_COMMERCIAL_FALLBACK: 'CONFIDENCE_LEGACY_COMMERCIAL_FALLBACK',
} as const;

export type ConfidenceReasonCode = (typeof CONFIDENCE_REASON)[keyof typeof CONFIDENCE_REASON];

/** Deterministic ordering for machine-readable reason code output. */
export const CONFIDENCE_REASON_ORDER: readonly ConfidenceReasonCode[] = [
  CONFIDENCE_REASON.PERSISTENCE_STABLE,
  CONFIDENCE_REASON.PERSISTENCE_NEW,
  CONFIDENCE_REASON.PERSISTENCE_CHANGED,
  CONFIDENCE_REASON.PERSISTENCE_MISSING_PREVIOUS,
  CONFIDENCE_REASON.PERSISTENCE_HISTORY_ABSENT,
  CONFIDENCE_REASON.PERSISTENCE_PROVIDER_HINT_FALLBACK,
  CONFIDENCE_REASON.PERSISTENCE_MATURITY_STATE_MISMATCH,
  CONFIDENCE_REASON.PERSISTENCE_HOURS_MISMATCH,
  CONFIDENCE_REASON.MATURITY_SOURCE_OBSERVATION_MISMATCH,
  CONFIDENCE_REASON.MATURITY_MATURE,
  CONFIDENCE_REASON.MATURITY_PARTIAL,
  CONFIDENCE_REASON.MATURITY_IMMATURE,
  CONFIDENCE_REASON.TELEMETRY_PARTIAL,
  CONFIDENCE_REASON.TELEMETRY_INSUFFICIENT,
  CONFIDENCE_REASON.TELEMETRY_NO_DATA,
  CONFIDENCE_REASON.TELEMETRY_NOT_APPLICABLE,
  CONFIDENCE_REASON.METRICS_PARTIAL,
  CONFIDENCE_REASON.OBSERVATION_WINDOW_INSUFFICIENT,
  CONFIDENCE_REASON.GOVERNANCE_CONTEXT_MISSING,
  CONFIDENCE_REASON.LEGACY_COMMERCIAL_FALLBACK,
  CONFIDENCE_REASON.STATUS_CEILING_APPLIED,
] as const;

export function sortConfidenceReasonCodes(codes: ConfidenceReasonCode[]): ConfidenceReasonCode[] {
  const orderIndex = new Map(CONFIDENCE_REASON_ORDER.map((code, index) => [code, index]));
  return [...codes].sort(
    (left, right) =>
      (orderIndex.get(left) ?? Number.MAX_SAFE_INTEGER) -
      (orderIndex.get(right) ?? Number.MAX_SAFE_INTEGER),
  );
}
