export const PERSISTENCE_REASON = {
  FIRST_OBSERVATION: 'PERSISTENCE_FIRST_OBSERVATION',
  FINGERPRINT_UNCHANGED: 'PERSISTENCE_FINGERPRINT_UNCHANGED',
  FINGERPRINT_CHANGED: 'PERSISTENCE_FINGERPRINT_CHANGED',
  PRIOR_HISTORY_MISSING: 'PERSISTENCE_PRIOR_HISTORY_MISSING',
  DUPLICATE_LOGICAL_OBSERVATION: 'PERSISTENCE_DUPLICATE_LOGICAL_OBSERVATION',
  INVALID_OBSERVATION_TIMESTAMP: 'PERSISTENCE_INVALID_OBSERVATION_TIMESTAMP',
  MISSING_OBSERVATION_TIMESTAMP: 'PERSISTENCE_MISSING_OBSERVATION_TIMESTAMP',
  MISSING_FINGERPRINT_INPUT: 'PERSISTENCE_MISSING_FINGERPRINT_INPUT',
  MALFORMED_PRIOR_HISTORY: 'PERSISTENCE_MALFORMED_PRIOR_HISTORY',
} as const;

export type PersistenceReasonCode = (typeof PERSISTENCE_REASON)[keyof typeof PERSISTENCE_REASON];
