export const POST_ACTION_VERIFICATION_REASON = {
  LEGACY_VERIFIED: 'LEGACY_VERIFIED',
  LEGACY_PARTIAL: 'LEGACY_PARTIAL',
  LEGACY_FAILED: 'LEGACY_FAILED',
  LEGACY_PENDING: 'LEGACY_PENDING',
  TELEMETRY_MISSING: 'TELEMETRY_MISSING',
  TELEMETRY_INADEQUATE: 'TELEMETRY_INADEQUATE',
  TELEMETRY_DEGRADED: 'TELEMETRY_DEGRADED',
  RECOMMENDATION_PERSISTS: 'RECOMMENDATION_PERSISTS',
  RECOMMENDATION_RESOLVED: 'RECOMMENDATION_RESOLVED',
  RECOMMENDATION_STATE_UNKNOWN: 'RECOMMENDATION_STATE_UNKNOWN',
  STATE_MISMATCH: 'STATE_MISMATCH',
  SAVINGS_BELOW_THRESHOLD: 'SAVINGS_BELOW_THRESHOLD',
  EXECUTION_NOT_COMPLETED: 'EXECUTION_NOT_COMPLETED',
  MEASURABLE_DEGRADATION: 'MEASURABLE_DEGRADATION',
  ROLLBACK_CANDIDATE_ADVISORY: 'ROLLBACK_CANDIDATE_ADVISORY',
  HEALTHY_POST_ACTION: 'HEALTHY_POST_ACTION',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
} as const;

export type PostActionVerificationReasonCode =
  (typeof POST_ACTION_VERIFICATION_REASON)[keyof typeof POST_ACTION_VERIFICATION_REASON];
