export const ACTION_POLICY_REASON = {
  READINESS_NOT_READY_BLOCKED: 'ACTION_POLICY_READINESS_NOT_READY_BLOCKED',
  READINESS_READY: 'ACTION_POLICY_READINESS_READY',
  PRODUCTION_INFRA_APPROVAL_REQUIRED: 'ACTION_POLICY_PRODUCTION_INFRA_APPROVAL_REQUIRED',
  PRODUCTION_INFRA_NOT_APPROVED: 'ACTION_POLICY_PRODUCTION_INFRA_NOT_APPROVED',
  PRODUCTION_APPROVED_ELIGIBLE: 'ACTION_POLICY_PRODUCTION_APPROVED_ELIGIBLE',
  PRODUCTION_REJECTED_BLOCKED: 'ACTION_POLICY_PRODUCTION_REJECTED_BLOCKED',
  SIMULATION_ALLOWED: 'ACTION_POLICY_SIMULATION_ALLOWED',
  SIMULATION_NOT_PRODUCTION: 'ACTION_POLICY_SIMULATION_NOT_PRODUCTION',
  ML_DETERMINISTIC_FALLBACK_PERMITTED: 'ACTION_POLICY_ML_DETERMINISTIC_FALLBACK_PERMITTED',
  ML_FALLBACK_REJECT_BLOCKED: 'ACTION_POLICY_ML_FALLBACK_REJECT_BLOCKED',
  ML_FAILED_SAFE_APPROVAL_UNCHANGED: 'ACTION_POLICY_ML_FAILED_SAFE_APPROVAL_UNCHANGED',
  ML_EXECUTED_NON_AUTHORITY: 'ACTION_POLICY_ML_EXECUTED_NON_AUTHORITY',
  ML_INELIGIBLE_NO_FALLBACK: 'ACTION_POLICY_ML_INELIGIBLE_NO_FALLBACK',
  AUTHORIZATION_BLOCKED: 'ACTION_POLICY_AUTHORIZATION_BLOCKED',
  MFA_REQUIRED_BLOCKED: 'ACTION_POLICY_MFA_REQUIRED_BLOCKED',
  STALE_PLAN_VERSION: 'ACTION_POLICY_STALE_PLAN_VERSION',
  MISSING_POLICY_SNAPSHOT: 'ACTION_POLICY_MISSING_POLICY_SNAPSHOT',
  APPROVAL_NOT_REQUIRED: 'ACTION_POLICY_APPROVAL_NOT_REQUIRED',
  /** @deprecated Override governance is implemented (see plan-metadata override history). Retained for historical records. */
  OVERRIDE_DEFERRED: 'ACTION_POLICY_OVERRIDE_DEFERRED',
  OVERRIDE_APPLIED: 'ACTION_POLICY_OVERRIDE_APPLIED',
  OVERRIDE_REASON_REQUIRED: 'ACTION_POLICY_OVERRIDE_REASON_REQUIRED',
  OVERRIDE_NOT_ELIGIBLE: 'ACTION_POLICY_OVERRIDE_NOT_ELIGIBLE',
  OVERRIDE_DECISION_UNCHANGED: 'ACTION_POLICY_OVERRIDE_DECISION_UNCHANGED',
} as const;

export type ActionPolicyReasonCode =
  (typeof ACTION_POLICY_REASON)[keyof typeof ACTION_POLICY_REASON];
