/**
 * Stable reason codes for the Sprint 4 governance regression safety gate.
 * Codes are append-only: never renumber or repurpose an existing code, and
 * never silently drop a code a historical release-gate report referenced.
 */
export const GOVERNANCE_REGRESSION_REASON = {
  // --- Task 2: canonical safety invariants -------------------------------
  INVARIANT_IMMATURE_NOT_READY: 'GOVREG_INVARIANT_IMMATURE_NOT_READY',
  INVARIANT_NOT_READY_CANNOT_EXECUTE: 'GOVREG_INVARIANT_NOT_READY_CANNOT_EXECUTE',
  INVARIANT_GOVERNANCE_FAIL_NOT_OVERRIDABLE_BY_ML:
    'GOVREG_INVARIANT_GOVERNANCE_FAIL_NOT_OVERRIDABLE_BY_ML',
  INVARIANT_HIGH_CONFIDENCE_NOT_APPROVAL:
    'GOVREG_INVARIANT_HIGH_CONFIDENCE_NOT_APPROVAL',
  INVARIANT_ML_EXECUTED_NOT_AUTHORITY: 'GOVREG_INVARIANT_ML_EXECUTED_NOT_AUTHORITY',
  INVARIANT_ML_FAILED_SAFE_MUST_NOT_WEAKEN_GOVERNANCE:
    'GOVREG_INVARIANT_ML_FAILED_SAFE_MUST_NOT_WEAKEN_GOVERNANCE',
  INVARIANT_APPROVAL_REQUIRED_MISSING_CANNOT_EXECUTE:
    'GOVREG_INVARIANT_APPROVAL_REQUIRED_MISSING_CANNOT_EXECUTE',
  INVARIANT_API_SUCCESS_NOT_OPTIMIZATION_SUCCESS:
    'GOVREG_INVARIANT_API_SUCCESS_NOT_OPTIMIZATION_SUCCESS',
  INVARIANT_INSUFFICIENT_EVIDENCE_NOT_SUCCESSFUL_VERIFICATION:
    'GOVREG_INVARIANT_INSUFFICIENT_EVIDENCE_NOT_SUCCESSFUL_VERIFICATION',
  INVARIANT_ROLLBACK_CANDIDATE_NOT_AUTHORIZATION:
    'GOVREG_INVARIANT_ROLLBACK_CANDIDATE_NOT_AUTHORIZATION',

  // --- Task 4: contradiction detection ------------------------------------
  CONTRADICTION_MATURITY_IMMATURE_READINESS_READY:
    'GOVREG_CONTRADICTION_MATURITY_IMMATURE_READINESS_READY',
  CONTRADICTION_GOVERNANCE_FAIL_EXECUTION_ELIGIBLE:
    'GOVREG_CONTRADICTION_GOVERNANCE_FAIL_EXECUTION_ELIGIBLE',
  CONTRADICTION_APPROVAL_REQUIRED_STATUS_NOT_REQUIRED:
    'GOVREG_CONTRADICTION_APPROVAL_REQUIRED_STATUS_NOT_REQUIRED',
  CONTRADICTION_VERIFICATION_INSUFFICIENT_EVIDENCE_MARKED_RESOLVED:
    'GOVREG_CONTRADICTION_VERIFICATION_INSUFFICIENT_EVIDENCE_MARKED_RESOLVED',
  CONTRADICTION_ROLLBACK_EVIDENCE_INSUFFICIENT_BUT_AUTHORIZED:
    'GOVREG_CONTRADICTION_ROLLBACK_EVIDENCE_INSUFFICIENT_BUT_AUTHORIZED',
  CONTRADICTION_CROSS_TENANT_DECISION_INPUT:
    'GOVREG_CONTRADICTION_CROSS_TENANT_DECISION_INPUT',

  // --- Evidence completeness / gate outcome -------------------------------
  EVIDENCE_MISSING_DECISION_READINESS: 'GOVREG_EVIDENCE_MISSING_DECISION_READINESS',
  EVIDENCE_MISSING_ACTION_POLICY: 'GOVREG_EVIDENCE_MISSING_ACTION_POLICY',
  EVIDENCE_MISSING_GOVERNANCE_CONTEXT: 'GOVREG_EVIDENCE_MISSING_GOVERNANCE_CONTEXT',
  EVIDENCE_MISSING_APPROVAL_CONTEXT: 'GOVREG_EVIDENCE_MISSING_APPROVAL_CONTEXT',

  GATE_SAFE: 'GOVREG_GATE_SAFE',
  GATE_BLOCKED_INVARIANT_VIOLATION: 'GOVREG_GATE_BLOCKED_INVARIANT_VIOLATION',
  GATE_BLOCKED_CONTRADICTION: 'GOVREG_GATE_BLOCKED_CONTRADICTION',
  GATE_INSUFFICIENT_EVIDENCE: 'GOVREG_GATE_INSUFFICIENT_EVIDENCE',
} as const;

export type GovernanceRegressionReasonCode =
  (typeof GOVERNANCE_REGRESSION_REASON)[keyof typeof GOVERNANCE_REGRESSION_REASON];
