export const ML_PRODUCTION_QUALIFICATION_REASON = {
  ML_QUAL_PRODUCTION_QUALIFIED: 'ML_QUAL_PRODUCTION_QUALIFIED',
  ML_QUAL_NOT_QUALIFIED_EMPTY_SNAPSHOT: 'ML_QUAL_NOT_QUALIFIED_EMPTY_SNAPSHOT',
  ML_QUAL_NOT_QUALIFIED_UNSAFE_OUTCOME: 'ML_QUAL_NOT_QUALIFIED_UNSAFE_OUTCOME',
  ML_QUAL_NOT_QUALIFIED_MISSING_REASON: 'ML_QUAL_NOT_QUALIFIED_MISSING_REASON',
  ML_QUAL_NOT_QUALIFIED_EXECUTED_WITHOUT_OUTPUT:
    'ML_QUAL_NOT_QUALIFIED_EXECUTED_WITHOUT_OUTPUT',
  ML_QUAL_NOT_QUALIFIED_AUTHORITY_CLAIM: 'ML_QUAL_NOT_QUALIFIED_AUTHORITY_CLAIM',
  ML_QUAL_DEFERRED_LIVE_PROVIDER: 'ML_QUAL_DEFERRED_LIVE_PROVIDER',
} as const;

export type MlProductionQualificationReasonCode =
  (typeof ML_PRODUCTION_QUALIFICATION_REASON)[keyof typeof ML_PRODUCTION_QUALIFICATION_REASON];
