export const DECISION_READINESS_REASON = {
  READY: 'DECISION_READINESS_READY',
  PERSISTENCE_STABLE: 'DECISION_READINESS_PERSISTENCE_STABLE',
  PERSISTENCE_NOT_STABLE: 'DECISION_READINESS_PERSISTENCE_NOT_STABLE',
  MATURITY_MATURE: 'DECISION_READINESS_MATURITY_MATURE',
  MATURITY_NOT_MATURE: 'DECISION_READINESS_MATURITY_NOT_MATURE',
  CONFIDENCE_HIGH: 'DECISION_READINESS_CONFIDENCE_HIGH',
  CONFIDENCE_NOT_HIGH: 'DECISION_READINESS_CONFIDENCE_NOT_HIGH',
  VALIDATION_INVALID: 'DECISION_READINESS_VALIDATION_INVALID',
  LONGITUDINAL_EVIDENCE_UNAVAILABLE: 'DECISION_READINESS_LONGITUDINAL_EVIDENCE_UNAVAILABLE',
  GOVERNANCE_CONTEXT_UNAVAILABLE: 'DECISION_READINESS_GOVERNANCE_CONTEXT_UNAVAILABLE',
  GOVERNANCE_CONVERGENCE_MISSING: 'DECISION_READINESS_GOVERNANCE_CONVERGENCE_MISSING',
  GOVERNANCE_CONVERGENCE_NOT_PRESERVED: 'DECISION_READINESS_GOVERNANCE_CONVERGENCE_NOT_PRESERVED',
} as const;

export type DecisionReadinessReasonCode =
  (typeof DECISION_READINESS_REASON)[keyof typeof DECISION_READINESS_REASON];
