export const GOVERNANCE_SAFETY_REASON = {
  GOVERNANCE_SAFETY_SAFE: 'GOVERNANCE_SAFETY_SAFE',
  GOVERNANCE_SAFETY_INSUFFICIENT_TELEMETRY: 'GOVERNANCE_SAFETY_INSUFFICIENT_TELEMETRY',
  GOVERNANCE_SAFETY_INSUFFICIENT_PRICING: 'GOVERNANCE_SAFETY_INSUFFICIENT_PRICING',
  GOVERNANCE_SAFETY_INSUFFICIENT_VERIFICATION_EVIDENCE:
    'GOVERNANCE_SAFETY_INSUFFICIENT_VERIFICATION_EVIDENCE',
  GOVERNANCE_SAFETY_INSUFFICIENT_INTELLIGENCE_CONTEXT:
    'GOVERNANCE_SAFETY_INSUFFICIENT_INTELLIGENCE_CONTEXT',
  GOVERNANCE_SAFETY_CROSS_TENANT_DENIED: 'GOVERNANCE_SAFETY_CROSS_TENANT_DENIED',
  GOVERNANCE_SAFETY_CONTRADICTION_DETECTED: 'GOVERNANCE_SAFETY_CONTRADICTION_DETECTED',
  GOVERNANCE_SAFETY_ML_HIGH_NON_AUTHORITY: 'GOVERNANCE_SAFETY_ML_HIGH_NON_AUTHORITY',
  GOVERNANCE_SAFETY_ML_FAILED_SAFE_PRESERVES_GOVERNANCE:
    'GOVERNANCE_SAFETY_ML_FAILED_SAFE_PRESERVES_GOVERNANCE',
} as const;

export type GovernanceSafetyReasonCode =
  (typeof GOVERNANCE_SAFETY_REASON)[keyof typeof GOVERNANCE_SAFETY_REASON];

export const GOVERNANCE_CONTRADICTION = {
  GOVERNANCE_CONTRADICTION_IMMATURE_WITH_READY:
    'GOVERNANCE_CONTRADICTION_IMMATURE_WITH_READY',
  GOVERNANCE_CONTRADICTION_NOT_READY_EXECUTION_ELIGIBLE:
    'GOVERNANCE_CONTRADICTION_NOT_READY_EXECUTION_ELIGIBLE',
  GOVERNANCE_CONTRADICTION_GOVERNANCE_FAIL_WITH_READY:
    'GOVERNANCE_CONTRADICTION_GOVERNANCE_FAIL_WITH_READY',
  GOVERNANCE_CONTRADICTION_GOVERNANCE_FAIL_EXECUTION_ELIGIBLE:
    'GOVERNANCE_CONTRADICTION_GOVERNANCE_FAIL_EXECUTION_ELIGIBLE',
  GOVERNANCE_CONTRADICTION_ML_OVERRIDES_GOVERNANCE_FAIL:
    'GOVERNANCE_CONTRADICTION_ML_OVERRIDES_GOVERNANCE_FAIL',
  GOVERNANCE_CONTRADICTION_ML_EXECUTED_IS_AUTHORITY:
    'GOVERNANCE_CONTRADICTION_ML_EXECUTED_IS_AUTHORITY',
  GOVERNANCE_CONTRADICTION_HIGH_CONFIDENCE_IMPLIES_APPROVED:
    'GOVERNANCE_CONTRADICTION_HIGH_CONFIDENCE_IMPLIES_APPROVED',
  GOVERNANCE_CONTRADICTION_APPROVAL_REQUIRED_NOT_REQUIRED:
    'GOVERNANCE_CONTRADICTION_APPROVAL_REQUIRED_NOT_REQUIRED',
  GOVERNANCE_CONTRADICTION_MISSING_APPROVAL_EXECUTION:
    'GOVERNANCE_CONTRADICTION_MISSING_APPROVAL_EXECUTION',
  GOVERNANCE_CONTRADICTION_REJECTED_APPROVAL_EXECUTION:
    'GOVERNANCE_CONTRADICTION_REJECTED_APPROVAL_EXECUTION',
  GOVERNANCE_CONTRADICTION_STALE_APPROVAL_EXECUTION:
    'GOVERNANCE_CONTRADICTION_STALE_APPROVAL_EXECUTION',
  GOVERNANCE_CONTRADICTION_EXECUTION_API_SUCCESS_VERIFIED:
    'GOVERNANCE_CONTRADICTION_EXECUTION_API_SUCCESS_VERIFIED',
  GOVERNANCE_CONTRADICTION_INSUFFICIENT_EVIDENCE_RESOLVED:
    'GOVERNANCE_CONTRADICTION_INSUFFICIENT_EVIDENCE_RESOLVED',
  GOVERNANCE_CONTRADICTION_ROLLBACK_CANDIDATE_AUTHORIZED:
    'GOVERNANCE_CONTRADICTION_ROLLBACK_CANDIDATE_AUTHORIZED',
  GOVERNANCE_CONTRADICTION_ROLLBACK_WITHOUT_AUTHORIZATION:
    'GOVERNANCE_CONTRADICTION_ROLLBACK_WITHOUT_AUTHORIZATION',
  GOVERNANCE_CONTRADICTION_ML_AUTHORIZED_ROLLBACK:
    'GOVERNANCE_CONTRADICTION_ML_AUTHORIZED_ROLLBACK',
  GOVERNANCE_CONTRADICTION_CROSS_TENANT_SCOPE:
    'GOVERNANCE_CONTRADICTION_CROSS_TENANT_SCOPE',
} as const;

export type GovernanceContradictionCode =
  (typeof GOVERNANCE_CONTRADICTION)[keyof typeof GOVERNANCE_CONTRADICTION];
